#!/usr/bin/env bash
# Build self-contained AEP skills
#
# Some skills share resources. To stay portable under the open Agent Skills
# format (https://skills.sh) — where the `skills` CLI installs each skill
# directory independently (symlink or copy) — every skill must be
# self-contained. This script materializes the canonical shared resources in
# skills/product-context/_shared/ into each skill that references them, so the
# committed tree has no cross-skill file dependencies.
#
# Authoring model:
#   - Edit shared resources ONCE in skills/product-context/_shared/{references,templates}/
#   - Run this script to materialize copies into each consuming skill
#   - Commit the generated copies (each is marked with a .aep-generated file)
#
# A skill is given a shared dir only when its SKILL.md actually references a
# file that lives in _shared/<dir>/. A skill's OWN (authored) references/ or
# templates/ — i.e. one without a .aep-generated marker — is never touched.
#
# Usage:
#   bash scripts/build-skills.sh            # materialize (idempotent)
#   bash scripts/build-skills.sh --check    # verify in sync; non-zero if stale
#   bash scripts/build-skills.sh --help

set -euo pipefail

MARKER=".aep-generated"
MARKER_BODY="Generated by scripts/build-skills.sh from skills/product-context/_shared/. Do not edit; edit _shared/ and rebuild."

show_help() {
  sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'
}

# --- Resolve repo + paths ---

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="$(dirname "$SCRIPT_DIR")"
PC="$REPO/skills/product-context"
SHARED="$PC/_shared"

CHECK=false
for arg in "$@"; do
  case "$arg" in
    --check) CHECK=true ;;
    --help|-h) show_help; exit 0 ;;
    *) echo "Unknown argument: $arg (try --help)"; exit 1 ;;
  esac
done

if [ ! -d "$SHARED" ]; then
  echo "ERROR: shared source not found: $SHARED"
  exit 1
fi

# Does $skillmd reference a file that lives in _shared/$shared ?
#   templates: any "templates/..." mention (templates are shared-only).
#   references: only a mention of a basename that actually exists in
#     _shared/references/ (so a skill citing its OWN references/ files, or a
#     cross-skill reference, does not trigger a shared copy).
needs_shared() {
  local skillmd="$1" shared="$2"
  if [ "$shared" = "templates" ]; then
    grep -qE '(^|[^A-Za-z0-9_/])templates/' "$skillmd"
    return
  fi
  local f bn
  for f in "$SHARED/$shared"/*; do
    [ -f "$f" ] || continue
    bn="$(basename "$f")"
    if grep -qF "references/$bn" "$skillmd"; then
      return 0
    fi
  done
  return 1
}

# Is $dir a generated copy (vs an authored, skill-owned dir)?
is_generated() { [ -f "$1/$MARKER" ]; }

STALE=0
WROTE=0

for skill_dir in "$PC"/*/; do
  name="$(basename "$skill_dir")"
  [ "$name" = "_shared" ] && continue
  skillmd="$skill_dir/SKILL.md"
  [ -f "$skillmd" ] || continue

  for shared in references templates; do
    src="$SHARED/$shared"
    [ -d "$src" ] || continue
    dst="$skill_dir$shared"

    if needs_shared "$skillmd" "$shared"; then
      # Skill needs the shared dir. Don't clobber an authored dir.
      if [ -d "$dst" ] && ! is_generated "$dst"; then
        continue
      fi
      if [ "$CHECK" = true ]; then
        if [ ! -d "$dst" ] || ! is_generated "$dst" \
           || ! diff -rq --exclude="$MARKER" "$src" "$dst" >/dev/null 2>&1; then
          echo "STALE: $name/$shared/ is missing or out of date"
          STALE=$((STALE + 1))
        fi
      else
        rm -rf "$dst"
        cp -R "$src" "$dst"
        printf '%s\n' "$MARKER_BODY" > "$dst/$MARKER"
        echo "  → $name/$shared/ (generated)"
        WROTE=$((WROTE + 1))
      fi
    else
      # Skill does not need it. A leftover GENERATED copy is stale.
      if [ -d "$dst" ] && is_generated "$dst"; then
        if [ "$CHECK" = true ]; then
          echo "STALE: $name/$shared/ is generated but no longer referenced"
          STALE=$((STALE + 1))
        else
          rm -rf "$dst"
          echo "  ✗ $name/$shared/ (removed, no longer referenced)"
          WROTE=$((WROTE + 1))
        fi
      fi
    fi
  done
done

if [ "$CHECK" = true ]; then
  if [ "$STALE" -gt 0 ]; then
    echo ""
    echo "ERROR: $STALE generated skill resource(s) are out of sync."
    echo "Run 'bash scripts/build-skills.sh' and commit the result."
    exit 1
  fi
  echo "build-skills: generated resources are in sync"
else
  echo "build-skills: done ($WROTE change(s))"
fi
